### ISSUE TITLE
Git doesn't hit the registry server specified for private bower

### ISSUE THREAD

**Issue by ldlnxs** [Hacklone/private-bower#110] opened 2015-02-12 09:36 UTC
What we encounter here are issues concerning the git part of bower. It seems a private registry tunnels it's git requests through some "localhost:6789" construct not documented anywhere. We can see the requests hitting our private-bower server, which is cloning packages and caching them without producing error messages.

It would be most helpful to have someone explaining the "localhost:6789" thing that somehow has to do with git. The error message we get is the following:

bower not-cached    git://localhost:6789/material-ui#*
bower resolve       git://localhost:6789/material-ui#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://localhost:6789/material-ui", exit code of #128

Additional error details:
fatal: unable to access 'https://localhost:6789/material-ui/': Failed connect to localhost:6789; Connection refused

I'm wondering why git doesn't hit the registry server specified for private bower ...

**Comment by Hacklone** [comment] 2015-02-12 18:45
Hey, 

The problem is that you've left the ```repositoryCache.git.host``` set to locahost. Change that to the name or ip address of your private-bower server,

Hope this helps. I'll close this issue for now, :)

**Closed by Hacklone** 2015-02-12 18:45 UTC

**Comment by ldlnxs** [comment] 2015-02-13 08:58
Thanx a lot.

**Comment by amadeoas** [comment] 2016-10-03 10:28
Please could you direct me where it is located the repositoryCache.git.host, which I assume to be a file?
I have my .bowerrc file with the registry set to my private one but it doesn't work

**Comment by amadeoas** [comment] 2016-10-03 10:35
I've found it. In mac (which I use) it is under /usr/local/lib/node_modules/private-bower/bower.conf.json
in parameter repositoryCache
